app = "hexdocs-sqlite"
primary_region = "waw"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]
  image = "ghcr.io/ruslandoga/hexdocs-sqlite-search:master"

[env]
  PHX_HOST = "hexdocs-sqlite.fly.dev"
  PHX_SERVER = "true"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
