name: bench

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: bench

    strategy:
      matrix:
        elixir: ["1.15"]
        otp: ["26"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        with:
          path: wat3.db.zst
          key: wat3.db.zst
          restore-keys: wat3.db.zst

      - run: curl -C - -O https://hexdocs-artifacts.s3.eu-central-003.backblazeb2.com/wat3.db.zst
      - run: zstd --rm wat3.db.zst -o wat3.db -d

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: bench-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            bench-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-
            bench-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-refs/heads/master-mix-

      - run: mix deps.get --only $MIX_ENV
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mkdir results
      - run: mix run bench/search.exs | tee results/search.txt
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/*.txt
