name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ["1.15"]
        otp: ["26"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        with:
          path: wat2.db.zst
          key: wat2.db.zst
          restore-keys: wat2.db.zst

      - run: curl -C - -O https://hexdocs-artifacts.s3.eu-central-003.backblazeb2.com/wat2.db.zst
      - run: zstd --rm wat2.db.zst -o wat2.db -d

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-
            test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-refs/heads/master-mix-

      - run: mix deps.get --only $MIX_ENV
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
